[phases.setup]
nixPkgs = ["python312", "google-chrome", "chromedriver"]

[phases.install]
cmds = ["python -m pip install --break-system-packages -r requirements.txt"]

[start]
cmd = "gunicorn app:app --bind 0.0.0.0:$PORT"
