[phases.setup]
nixPkgs = ["python312", "python312Packages.pip", "google-chrome", "chromedriver"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "gunicorn app:app --bind 0.0.0.0:$PORT"
